set number
set tabstop=8
syntax on
filetype plugin indent on



set rtp+=/home/jlima/.local/lib/python2.7/site-packages/powerline/bindings/vim
set laststatus=2
set showtabline=1
set noshowmode
set t_Co=256

