---
- hosts: all_datacenters
  connection: local
  gather_facts: no

  tasks:
    # - name: get facts list
    #   ios_facts:
    #     gather_subset:
    #       - "config"
    #   register: my_facts

    # - debug:
    #     var: my_facts.ansible_facts.ansible_net_config.splitlines()[0:20]
    # - name: get facts list
      # ios_command:
        # commands:
          # - sho version 
          # - sho interface 
          # - sho clock 
      # register: my_commands
    # - debug:
        # var: my_commands.stdout_lines
            
    - name: get facts list
      ios_command:
        commands:
          - sho run | i ntp server
          
      register: my_dnservers
    - debug:
        var: my_dnservers.stdout_lines
        
    - name: remove all dns servers 
      with_items: "{{ my_dnservers.stdout_lines }}"
      ios_config:
        lines:
          - no {{ item }}
          
           
      

    # - debug:
    #     var: my_facts.ansible_facts.ansible_net_config.splitlines()[0:20]

