---
- hosts: all_datacenters
  connection: local
  gather_facts: no

  tasks:
    - name: loop through show run output
      ios_command:
        commands:
          - sho run | i ntp server
      register: my_var

    - debug:
        var: my_var.stdout_lines

    - name: remove all dns servers
      with_items: "{{ my_var.stdout_lines }}"
      ios_config:
        lines:
          - no {{ item }}

    # - name: get facts list
    #   ios_facts:
    #     gather_subset:
    #       - "config"
    #   register: my_facts

    # - debug:
    #     var: my_facts.ansible_facts.ansible_net_config.splitlines()[0:20]
    # - name: get facts list
      # ios_command:
        # commands:
          # - sho version
          # - sho interface
          # - sho clock
      # register: my_commands
    # - debug:
        # var: my_commands.stdout_lines




    # - debug:
    #     var: my_facts.ansible_facts.ansible_net_config.splitlines()[0:20]

