---
- hosts: all_datacenters
  connection: local
  gather_facts: no

  # vars_files:
  #   - infrastructure_servers.yml

  tasks:
    - name: deploy access list
      ios_config:
        lines:
          - permit tcp any any eq 22
          - permit udp any any eq domain
          - deny   tcp host 192.162.1.2 any eq 8888
          - permit udp 192.162.0.0 0.0.0.255 any eq 1821
          - permit udp 192.162.0.0 0.0.0.255 any eq 1822
        parents: ip access-list extended DC1EAST_ACL-IN
        match: exact
        # before:
        #   - interface GigabitEthernet1/0
        #   - no ip access-group DC1EAST_ACL-IN in
        #   - no ip access-list extended DC1EAST_ACL-IN
        # after:
        #   - interface GigabitEthernet1/0
        #   - ip access-group DC1EAST_ACL-IN in
        before:
          - no ip access-list extended DC1EAST_ACL-IN
        backup: yes

    - name: bind ACL to interface list
      with_items: "{{ global_servers.wan_interfaces }}"
      ios_config:
        lines:
          - ip access-group DC1EAST_ACL-IN in
        parents: interface {{ item }}

    - name: deploy dns servers
      with_items: "{{ global_servers.dns_servers }}"
      ios_config:
        lines:
          - ip name-server {{ item }}

    - name: deploy ntp servers
      with_items: "{{ global_servers.ntp_servers }}"
      ios_config:
        lines:
          - "{{ item }}"



    - name: save running to startup when modified
      ios_config:
        save_when: modified

