---
- hosts: dc1east,dc2west
  connection: local
  gather_facts: no

  # vars_files:
  #   - infrastructure_servers.yml

  tasks:
    - name: deploy access list
      ios_config:
        lines:
          - permit tcp any any eq 22
          - permit udp any any eq domain
          - deny   tcp host 192.162.1.2 any eq 8888
          - permit udp 192.162.0.0 0.0.0.255 any eq 1821
          - permit udp 192.162.0.0 0.0.0.255 any eq 1822
        parents: ip access-list extended DC1EAST_ACL-IN
        match: exact
        # before:
        #   - interface GigabitEthernet1/0
        #   - no ip access-group DC1EAST_ACL-IN in
        #   - no ip access-list extended DC1EAST_ACL-IN
        # after:
        #   - interface GigabitEthernet1/0
        #   - ip access-group DC1EAST_ACL-IN in
        before:
          - no ip access-list extended DC1EAST_ACL-IN
        backup: yes

    - name: bind ACL to interface list
      with_items: "{{ wan_interfaces }}"
      ios_config:
        lines:
          - ip access-group DC1EAST_ACL-IN in
        parents: interface {{ item }}

    - name: deploy dns servers
      with_items: "{{ global_servers.dns_servers }}"
      ios_config:
        lines:
          - "{{ item }}"

    - name: get current ntp servers
      ios_command:
        commands:
          - show run | i ntp server
      register: current_ntp

    # - debug:
    #     var: current_ntp.stdout_lines

    - name: get current dns servers
      ios_command:
        commands:
          - show run | i name-server
      register: current_dns


    - name: deploy ntp servers
      with_items: "{{ global_servers.ntp_servers }}"
      ios_config:
        lines:
          - "{{ item }}"

    - name: remove non-compliant ntp servers
      with_items: "{{ current_ntp.stdout_lines }}"
      ios_config:
        lines:
          - no {{ item }}
      when: '(item not in global_servers.ntp_servers) and (global_servers.ntp_servers != "")'

    - name: remove non-compliant dns servers
      with_items: "{{ current_dns.stdout_lines }}"
      ios_config:
        lines:
          - no {{ item }}
      when: 'item not in global_servers.dns_servers'

    - name: save running to startup when modified
      ios_config:
        save_when: modified

